#!/bin/bash

set -euo pipefail

# Fairseq expects six files:
# Two train, two dev, two test, each distinguished by prefixes.
# One file is the source and one is the target, distinguished by suffixes.
readonly DATA=../../data

tsv() {
    for TASK in train dev test; do
        for TSV in "${DATA}/${TASK}/"*"_${TASK}.tsv"; do
            # Separates graphemes with spaces.
            cut -f1 "${TSV}" | \
                sed 's/./& /g' \
                > "${TASK}".$(basename ${TSV%_${TASK}.tsv}).graphemes
            # Phonemes are already separated intelligently in WikiPron.
            cut -f2 "${TSV}" \
                > "${TASK}.$(basename ${TSV%_${TASK}.tsv}).phonemes"
        done
    done
}

bin() {
    # Here we leave out test data because it's not provided yet.
    for DEVPATH in dev.*.graphemes; do  # e.g., dev.kor_phonetic.graphemes
        LANGUAGE="$(echo "${DEVPATH}" | cut -d'.' -f2)"
        fairseq-preprocess \
            --source-lang="${LANGUAGE}.graphemes" \
            --target-lang="${LANGUAGE}.phonemes" \
            --trainpref=train \
            --validpref=dev \
            --testpref=test \
            --tokenizer=space \
            --thresholdsrc=5 \
            --thresholdtgt=5 \
            --destdir="data-bin/${LANGUAGE}"
    done
}

main() {
    tsv
    bin
    rm *.{graph,phon}emes
}

main
