#!/bin/bash

set -eou pipefail

readonly SEED=212
readonly DATA=../../data
readonly RANDOM_STARTS=25

mkdir -p checkpoints

for TRAIN_TSV in "${DATA}/train/"*"_train.tsv"; do
    LANGUAGE="$(basename $TRAIN_TSV _train.tsv)"
    mkdir -p "checkpoints/${LANGUAGE}"
    DEV_TSV="${TRAIN_TSV//train/dev}"
    TEST_TSV="${TRAIN_TSV//train/test}"
    # Output symbols.
    PHONES="${LANGUAGE}_phones.sym"
    cut -f2 "${TRAIN_TSV}" "${DEV_TSV}" | ngramsymbols > "${PHONES}"
    # Alignments.
    ./align.py \
        --seed="${SEED}" \
        --random_starts="${RANDOM_STARTS}" \
        --tsv_path="${TRAIN_TSV}" \
        --output_token_type="${PHONES}" \
        --encoder_path="${LANGUAGE}.enc" \
        --far_path="${LANGUAGE}.far"
    # Loops over LM orders from 3 (trigram) to 9. 
    for ORDER in $(seq 3 9); do
        MODEL="checkpoints/${LANGUAGE}/${ORDER}.fst"
        # NGram model.
        ./model \
            --encoder_path="${LANGUAGE}.enc" \
            --far_path="${LANGUAGE}.far" \
            --fst_path="${MODEL}" \
            --order="${ORDER}"
        # Evaluation.
        ./predict \
            --fst_path="${MODEL}" \
            --input_path="${DEV_TSV}" \
            --output_token_type="${PHONES}" \
            --output_path="${LANGUAGE}.txt"
        ./evaluate \
            --gold_path="${DEV_TSV}" \
            --hypo_path="${LANGUAGE}.txt" \
            > "checkpoints/${LANGUAGE}/dev-${ORDER}.res"
        ./predict \
            --fst_path="${MODEL}" \
            --input_path="${TEST_TSV}" \
            --output_token_type="${PHONES}" \
            --output_path="${LANGUAGE}.txt"
        ./evaluate \
            --gold_path="${TEST_TSV}" \
            --hypo_path="${LANGUAGE}.txt" \
            > "checkpoints/${LANGUAGE}/test-${ORDER}.res"
    done
    rm "${PHONES}" "${LANGUAGE}.enc" "${LANGUAGE}.far" "${LANGUAGE}.txt"
done
